apiVersion: v2
name: cray-vault
version: 1.0.5
description: Cray Vault for secure secret stores
keywords:
  - cray-vault
home: https://github.com/Cray-HPE/cray-vault
appVersion: 1.5.5
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Updated images to CSM patched versions
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-vault/issues/3
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-vault/pull/2
  artifacthub.io/images: |
    - name: kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.9
    - name: ubuntu
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/ubuntu:focal
    - name: vault
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/vault:1.5.5
    - name: bank-vaults
      image: artifactory.algol60.net/csm-docker/stable/ghcr.io/banzaicloud/bank-vaults:1.8.0
    - name: statsd-exporter
      image: artifactory.algol60.net/csm-docker/stable/docker.io/prom/statsd-exporter:v0.18.0
  artifacthub.io/license: MIT
