#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
name: cray-vault
version: 1.6.1
description: Cray Vault for secure secret stores
keywords:
  - cray-vault
home: https://github.com/Cray-HPE/cray-vault
maintainers:
  - name: kburns-hpe
  - name: rnoska-hpe
appVersion: 1.10.8
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Updated images to CSM patched versions
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-vault/issues/3
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-vault/pull/2
  artifacthub.io/images: |
    - name: kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
    - name: ubuntu
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/ubuntu:focal
    - name: vault
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/vault:1.10.8
    - name: bank-vaults
      image: artifactory.algol60.net/csm-docker/stable/ghcr.io/banzaicloud/bank-vaults:1.16.0
    - name: statsd-exporter
      image: artifactory.algol60.net/csm-docker/stable/docker.io/prom/statsd-exporter:v0.18.0
  artifacthub.io/license: MIT
